# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RacoreCli < Formula
  desc "Racore Cloud CDN CLI with MCP protocol support for AI agents"
  homepage "https://github.com/yingcaihuang/Racore-cli"
  version "0.3.3"
  license "MIT"

  on_macos do
    url "https://github.com/yingcaihuang/Racore-cli/releases/download/v0.3.3/racore-cli_0.3.3_darwin_all.tar.gz"
    sha256 "60ae18bc538f2d95f3e59cf6e0bd2f167c42bf5c3258701b89d58fa69c523d37"

    define_method(:install) do
      bin.install "racore-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yingcaihuang/Racore-cli/releases/download/v0.3.3/racore-cli_0.3.3_linux_amd64.tar.gz"
      sha256 "e193c2131f422fd7132f002f73c07fbae47fe5c50cd1c64d4b61cc63c4431aee"
      define_method(:install) do
        bin.install "racore-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yingcaihuang/Racore-cli/releases/download/v0.3.3/racore-cli_0.3.3_linux_arm64.tar.gz"
      sha256 "044c6c52b965774df5972aee97f5ad571f843f831193f593fa2f8505aa537f15"
      define_method(:install) do
        bin.install "racore-cli"
      end
    end
  end

  test do
    system "#{bin}/racore-cli", "--version"
  end
end
