# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RacoreCli < Formula
  desc "Racore Cloud CDN CLI with MCP protocol support for AI agents"
  homepage "https://github.com/yingcaihuang/Racore-cli"
  version "0.3.4"
  license "MIT"

  on_macos do
    url "https://github.com/yingcaihuang/Racore-cli/releases/download/v0.3.4/racore-cli_0.3.4_darwin_all.tar.gz"
    sha256 "a9a3bd3ee0cbff5e8f61c477db485b6007c9b5b503cec2d0894003234baae1ab"

    define_method(:install) do
      bin.install "racore-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yingcaihuang/Racore-cli/releases/download/v0.3.4/racore-cli_0.3.4_linux_amd64.tar.gz"
      sha256 "dcd7902cba7f889171b8d0d6a991269e1bd743e860d7f4d5275ff0e64343e2a2"
      define_method(:install) do
        bin.install "racore-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yingcaihuang/Racore-cli/releases/download/v0.3.4/racore-cli_0.3.4_linux_arm64.tar.gz"
      sha256 "9a97a0e52f5a0a10f8f210096dae67a385791a9e0e1880adc67e0302650cb975"
      define_method(:install) do
        bin.install "racore-cli"
      end
    end
  end

  test do
    system "#{bin}/racore-cli", "--version"
  end
end
